### PR TITLE
chore(renovate): group all linter-related PRs together

### PR DESCRIPTION
**Pull request by boneskull**
This is a good idea, since ESLint upgrades do not usually work in a vacuum. What with the peer dependencies and all...

* * *

Basically, any package matching `eslint*` will be grouped together into a single PR. This can avoid problems if, say, ESLint updates, but it's now out-of-range of a plugin.

### CODE REVIEW

**Comment by boneskull** [comment]
I have a few other things I'd like to throw in that config:

- Maybe rename it to `.github/renovaterc.json5` so we can add comments
- extend `helpers:pinGitHubActionsDigests` to upgrade GH actions to specific SHAs
- extend `:semanticCommits` since we already seem to be using them

also, consider:

- add `transitiveRemediation: true` and extend `:enableVulnerabilityAlerts` coupled with a scheduled job to update `package-lock.json`.  see [here](https://github.com/renovatebot/renovate/discussions/24816#discussioncomment-7155513) for how this works.
- if we trust our actions, enable `:automergeDigest`. but that might mean loosening the reins on the branch protection (right now all PRs require review)

**Comment by nzakas** [comment]
> I have a few other things I'd like to throw in that config:
> 
>     * Maybe rename it to `.github/renovaterc.json5` so we can add comments

Fine with me.

>     * extend `helpers:pinGitHubActionsDigests` to upgrade GH actions to specific SHAs

I'm not sure this is worth it, especially for first-party actions.

>     * extend `:semanticCommits` since we already seem to be using them

Seems okay, though not sure how it would change our current experience?


> also, consider:
> 
>     * add `transitiveRemediation: true` and extend `:enableVulnerabilityAlerts` coupled with a scheduled job to update `package-lock.json`.  see [here](https://github.com/renovatebot/renovate/discussions/24816#discussioncomment-7155513) for how this works.

Not quite sure I understand what all this does, nor how valuable it is. Until we do a release, it really doesn't matter what's in `package-lock.json`.

>     * if we trust our actions, enable `:automergeDigest`. but that might mean loosening the reins on the branch protection (right now all PRs require review)

I'm not sure this is valuable enough to loosen branch protection.

**Comment by boneskull** [comment]
@nzakas 

> > * extend `:semanticCommits` since we already seem to be using them
> Seems okay, though not sure how it would change our current experience?

This appears to be the default value, so not needed.

> > * add `transitiveRemediation: true` and extend `:enableVulnerabilityAlerts` coupled with a scheduled job to update `package-lock.json`.  see [here](https://github.com/renovatebot/renovate/discussions/24816#discussioncomment-7155513) for how this works.
> Not quite sure I understand what all this does, nor how valuable it is. Until we do a release, it really doesn't matter what's in package-lock.json.

Yes, `package-lock.json` is consumed in our development and CI environments only, but it's worth keeping those environments up-to-date.  It's certainly unlikely that we'll get bit by something, but it's a good security posture nonetheless (full disclosure: my job requires me to be a little paranoid).  I'm happy to try to set this up and keep it working, and am open to re-evaluate later if it reveals itself to be burdensome?

> > * if we trust our actions, enable `:automergeDigest`. but that might mean loosening the reins on the branch protection (right now all PRs require review)
> I'm not sure this is valuable enough to loosen branch protection.

works for me

**Comment by nzakas** [comment]
> I'm happy to try to set this up and keep it working, and am open to re-evaluate later if it reveals itself to be burdensome?

Does that require loosening branch protections, or will just create a new PR? If the latter, then :+1:

**Comment by boneskull** [comment]
> Does that require loosening branch protections, or will just create a new PR? If the latter, then 👍

Yeah, this is a new PR that would enable the transitive remediation in Renovate and setup a scheduled job to update the lockfile.

**Comment by nzakas** [comment]
All right, let's see how this goes. :)

**Pull request merged**
