### PR TITLE
fix: Creates CJS type declarations for CJS export.

### LINKED ISSUE #136: TypeScript cannot find typings for CommonJS version of this package
Hi, I am trying to use this library with TypeScript. In my case **I need to get CommonJS output from TypeScript source code**.

I also tried using a config similar to the one in this project:

```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true
  }
}
```

But in case of `.ts` and `.cjs` files I have error:

```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@humanwhocodes/env")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to 'stackblitz:/package.json'.(1479)
```

Here is an example with reproduction:
https://stackblitz.com/edit/typescript-node-hpq7zy?file=src%2Findex.ts

In this example I also added another dual (ESM+CJS) package for comparison.

Screenshot

For some reason TypeScript can find declarations for ESM version of `humanwhocodes/env` but cannot find same declarations for CommonJS

**You can see problem in `.ts` and in `.cjs` files** - just run `npm run check`

### Additional information

- I can't just change extension to `.mts` and I also can't just add `"type": "module"` for my project, I need exactly CommonJS output and that is why I configured TypeScript this way

- With provided TS config `import` will be replaced by `require` and it is exactly what I needed for output code

- Package `humanwhocodes/env` works with CommonJS, problem is just with TypeScript type checking.

### PR DESCRIPTION
**Pull request by nzakas**
Added an additional `tsconfig` file that just outputs a CJS version of the `.d.ts` file to accompany the CJS version of the module.

fixes #136

### CODE REVIEW

**Comment by nzakas** [comment]
@boneskull what do you think of this approach to generating types for the CommonJS entrypoint?

**Comment by boneskull** [comment]
OK, I think this is fine.

I wonder if there is a rollup-adjacent tool that'd help w/ shipping dual-module-system packages.  

I use [tshy](https://npm.im/tshy) for this, which just uses `tsc` instead of a bundler.  It also provides an escape-hatch for ES-specific stuff (e.g., `import.meta`).

**Review by boneskull — APPROVED** [review]
lgtm

**Comment by boneskull** [comment]
@nzakas You know, I think we can just copy `dist/env.d.ts` to `dist/env.d.cts` and it should work.  I don't think we need to run `tsc` again.

**Comment by boneskull** [comment]
relevant: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#respecting-file-extensions-and-packagejson-in-other-module-modes

**Pull request merged**
