### PR TITLE
chore(renovate): fix config syntax

### PR DESCRIPTION
**Pull request by boneskull**
`eslint-plugin-jsonc` would have caught this

### CODE REVIEW

**Comment by boneskull** [comment]
Closes #122

**Comment by boneskull** [comment]
@nzakas As mentioned, I've had good luck with [eslint-plugin-jsonc](https://npm.im/eslint-plugin-jsonc) for both Renovate configs _and_ `tsconfig.json` (which is also parsed as JSON5/JSONC)

**Review by nzakas — APPROVED** [review]
For some reason I thought trailing commas were allowed in JSON5. 🤷‍♂️

**Comment by boneskull** [comment]
they are! but the problem was a missing comma 🙂

**Pull request merged**
